### ISSUE TITLE
Support for rewrite/instrumentation with dexlib2

### ISSUE THREAD

**Issue by Foo-Manroot** [google/smali#59]
Hi

I've been trying for several days already, but can't seem to find my way around how `dexlib2` is supposed to work...

My goal is to get a .dex file and modify a single method and rebuild it to obtain a runnable APK.
Basically, I'm trying to improve my script here: https://github.com/Foo-Manroot/apk-patcher

I could improve it by disassembling everything (`Baksmali.disassembleDexFile ()`), modifying the text file (`<whatever>.smali`) and assemble it back again (`Smali.assemble ()`).
This approach does work, but is obviously not ideal.

My idea was to use dexlib2 directly; but every time I write the resulting .dex file, it seems to be corrupted.
When `baksmali`ng that re-assembled .dex, I get a lot of failures like this, which seem to be related with wrong indices on the DebugInfo section (?):
```
Error occurred while disassembling class Landroidx.appcompat.view.menu.MenuAdapter; - skipping class
com.android.tools.smali.util.ExceptionWithContext: Invalid string index 50184, not in [0, 43639)
        at com.android.tools.smali.util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
        at com.android.tools.smali.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:168)
        at com.android.tools.smali.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
        at com.android.tools.smali.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:118)
        at com.android.tools.smali.baksmali.Baksmali.disassembleClass(Baksmali.java:169)
        at com.android.tools.smali.baksmali.Baksmali.access$000(Baksmali.java:54)
        at com.android.tools.smali.baksmali.Baksmali$1.call(Baksmali.java:84)
        at com.android.tools.smali.baksmali.Baksmali$1.call(Baksmali.java:82)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Invalid string index 50184, not in [0, 43639)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.getOffset(DexBackedDexFile.java:347)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:322)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.getOptional(DexBackedDexFile.java:340)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.getOptional(DexBackedDexFile.java:319)
        at com.android.tools.smali.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl$4.readNextItem(DebugInfo.java:304)
        at com.android.tools.smali.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl$4.readNextItem(DebugInfo.java:302)
        at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeIterator.next(VariableSizeIterator.java:79)
        at com.android.tools.smali.dexlib2.dexbacked.util.ParameterIterator.next(ParameterIterator.java:74)
        at com.android.tools.smali.dexlib2.dexbacked.util.ParameterIterator.next(ParameterIterator.java:45)
        at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:146)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:249)
        at com.android.tools.smali.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:100)
        ... 10 more
Error while processing method Landroidx/appcompat/view/menu/MenuAdapter;->getView(ILandroid/view/View;Landroid/view/ViewGroup;)Landroid/view/View;
```
Similar errors happen with other tools like `dexdump`

That stack trace was generated by simply trying to `$ baksmali disassemble output.dex`, with output.dex being generated like this:
```
Opcodes opcodes = Opcodes.forDexVersion (38);
DexBackedDexFile dex = DexFileFactory.loadDexFile ("classes.dex", opcodes);
DexFileFactory.writeDexFile ("output.dex", dex);
```

This simple example should've generated a valid file, shouldn't it?
I attach the original classes.dex and my output.dex, just in case it helps. They come from a sample app I just created with Android Studio, after unzipping the resulting app-debug.apk:
[dex files.zip](https://github.com/user-attachments/files/15751941/dex.files.zip)

I tried multiple methods:
 - Using [DexRewriter](https://github.com/google/smali/blob/5f8b0491e8d925396873292a98c1d3bfd3e2c44a/dexlib2/src/main/java/com/android/tools/smali/dexlib2/rewriter/DexRewriter.java#L61) (that snippet in the comment is using the old API, btw) 
 - Recreating the whole file with a `DexPool`, as suggested [here](https://stackoverflow.com/a/77201617)
 - Taking inspiration from other implementations like [this](https://github.com/alibaba/atlas/blob/c20c5b83f67b9a14fb597d59a287ec7a3e5bdbac/atlas-gradle-plugin/dexpatch/src/main/java/com/taobao/android/tools/PatchFieldTool.java#L464), [here](https://gist.github.com/JesusFreke/6945806),  [this issue](https://github.com/JesusFreke/smali/issues/874), ... all of them seem to be using an old API, maybe that's why they don't work anymore (?)
 - Navigating the Javadoc and trying a thousand different things, but I get a bit lost on the API (i.e.: what's the purpose of the seemingly duplicated functionality like ImmutableClassDef, BuilderClassDef, DexBackedClassDef, RewrittenClassDef, ... [this](https://stackoverflow.com/a/77201617) StackOverflow answer has some pointers, but don't go into details into how to properly perform the conversion from one to the other.

Could you help me figure out how to properly use dexlib2, or point out what I might be doing wrong?
Thanks in advance

**Comment by melcz** [comment]
Have you checked RewriteArrayTypeTest?  There's usage of the Rewriter there

**Comment by Foo-Manroot** [comment]
Hi, @melcz , thanks for the reply.

It looks like my problem wasn't that I didn't know how to use the rewrite API, but that the `DexWriter` was producing broken files.

I pinpointed it to a couple of lines and reverted that change (I can't create a proper PR due to the CLA, though); so now all the examples I cited above should be working fine.
I am therefore closing this issue.

Thanks for the support!
