### ISSUE TITLE
Unexpected container offset in header

### ISSUE THREAD

**Issue by rashpel77** [google/smali#80]
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.android.tools.smali.dexlib2.util.DexUtil$InvalidFile: Unexpected container offset in header
	at brut.androlib.ApkDecoder.decode(SourceFile:0)
	at brut.apktool.Main.main(SourceFile:0)
Caused by: java.util.concurrent.ExecutionException: com.android.tools.smali.dexlib2.util.DexUtil$InvalidFile: Unexpected container offset in header
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	... 2 more
Caused by: com.android.tools.smali.dexlib2.util.DexUtil$InvalidFile: Unexpected container offset in header
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer.getEntries(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer.getDexEntryNames(SourceFile)
	at brut.androlib.ApkDecoder.decodeSourcesSmaliJob(SourceFile:0)
	at brut.androlib.ApkDecoder.lambda$decodeSourcesSmali$0(SourceFile)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[*] ---> Decompilation error

After editing smali in .apk it is assembled, everything is fine here. The error appears when parsing this .apk again. api35 apktool 2.10.1 Is the encoding broken?

**Comment by IgorEisberg** [comment]
smali outputs invalid dex 041 files for API 35.
If used on actual runtime, Zygote crashes with "Header size is 112 but 120 was expected".
Seems like smali is building dex 041 with the legacy Header, rather than Header41 which is 8 bytes larger...
https://cs.android.com/android/platform/superproject/main/+/main:art/libdexfile/dex/dex_file.h;l=187
